### ISSUE TITLE
Test model eos4avb

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4avb#2]
This model is ready for testing!

**Comment by carcablop** [comment]
Hello @GemmaTuron 
I have tested the model in Google Colab.: 
Fetch successfully in google colab
Serve successfully
run successfully passing "eml_canonical.csv" as input. For this input I have the following output: 
[eos4avb_output.csv](https://github.com/ersilia-os/eos4avb/files/10680936/eos4avb_output.csv)

What do the numbers that are in the header of the columns of the output file mean?

When I run from colab passing a single molecule as input, I get an error on the output like this: 
[log_colab1molelcula_eos4avb.txt](https://github.com/ersilia-os/eos4avb/files/10680949/log_colab1molelcula_eos4avb.txt)

I have tested the model in my CLI.
Fetch successfully in my CLI : 
[fetch_eos4avb.txt](https://github.com/ersilia-os/eos4avb/files/10680953/fetch_eos4avb.txt)

Serve successfully
unsuccessful run for eml_canonical.csv (possibly a bug in my ersilia as I've made some changes to the output adapter)

**Comment by carcablop** [comment]
On my local system,in my workspace,  some images of molecules were also generated as outputs, when I tried to run the model. If the images are going to be stored, it is better to keep them in a folder.

![imagen](https://user-images.githubusercontent.com/17841081/217412663-4b8c26a5-25ed-434b-9311-55b329b2fbba.png)

**Comment by GemmaTuron** [comment]
Thanks for the testing @carcablop !

@DhanshreeA can you check and provide feedback?

**Comment by DhanshreeA** [comment]
Hi @carcablop , thank you for your thorough testing. Let me answer your questions one by one.

>What do the numbers that are in the header of the columns of the output file mean?

I think this is a problem as well, I am not writing a header in the output.csv in the model's `main.py` so it seems that the output of the first input in the CSV is in fact being used to populate column headers for the first input. At first I thought that's coming from the CLI but it's not :sweat_smile: 

> When I run from colab passing a single molecule as input, I get an error on the output like this:

This above problem is probably causing it to fail with a CSV having a single input. I'll get to fixing these ASAP.

>  unsuccessful run for eml_canonical.csv (possibly a bug in my ersilia as I've made some changes to the output adapter)

For the CLI on your local, I suggest stashing your local changes using `git stash .` and then updating ersilia by pulling changes from remote and then running it again? For restoring your changes you can use `git stash pop` afterwards. If you would like, you could also post the errors from your changes here so we can understand them together.

> On my local system,in my workspace, some images of molecules were also generated as outputs, when I tried to run the model. If the images are going to be stored, it is better to keep them in a folder.

This is a problem, thanks for bringing it up. I had included some clean up in other ImageMol models and it slipped my mind to include it in this one. I'll fix this ASAP. Ideally it should not be storing these intermediate artifacts on your machine at all.

**Comment by DhanshreeA** [comment]
Both the issues above have been fixed here:
#5 (to be merged first) and #6

The testing pipeline is failing because of the LFS issue we are already aware of across other repos. https://github.com/ersilia-os/eos4avb/actions/runs/4123388955/jobs/7121351410#step:8:2281

I have tested these fixes with 5 inputs and then with a single input:

Single input: [eos4avb_output_1.csv](https://github.com/ersilia-os/eos4avb/files/10684857/eos4avb_output_1.csv)
Five inputs: [eos4avb_output_5.csv](https://github.com/ersilia-os/eos4avb/files/10684859/eos4avb_output_5.csv)

Because of the header, the files the line count in the files should be 1 + num_inputs, this can be verified either by looking at the files or just getting a line count by `cat <output.csv> | wc -l`

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA !

Thanks, this looks good. I'll update you on the Git LFS issue when I have more news, I'm on top of that!
@Femme-js can you test the model with the new changes and confirm all is working? Thanks!

**Comment by carcablop** [comment]
> Hi @carcablop , thank you for your thorough testing. Let me answer your questions one by one.
> 
> > What do the numbers that are in the header of the columns of the output file mean?
> 
> I think this is a problem as well, I am not writing a header in the output.csv in the model's `main.py` so it seems that the output of the first input in the CSV is in fact being used to populate column headers for the first input. At first I thought that's coming from the CLI but it's not 😅
> 
> > When I run from colab passing a single molecule as input, I get an error on the output like this:
> 
> This above problem is probably causing it to fail with a CSV having a single input. I'll get to fixing these ASAP.
> 
> > unsuccessful run for eml_canonical.csv (possibly a bug in my ersilia as I've made some changes to the output adapter)
> 
> For the CLI on your local, I suggest stashing your local changes using `git stash .` and then updating ersilia by pulling changes from remote and then running it again? For restoring your changes you can use `git stash pop` afterwards. If you would like, you could also post the errors from your changes here so we can understand them together.
> 
> > On my local system,in my workspace, some images of molecules were also generated as outputs, when I tried to run the model. If the images are going to be stored, it is better to keep them in a folder.
> 
> This is a problem, thanks for bringing it up. I had included some clean up in other ImageMol models and it slipped my mind to include it in this one. I'll fix this ASAP. Ideally it should not be storing these intermediate artifacts on your machine at all.

Thank you @DhanshreeA . This runs fine in my CLI, I can fetch, serve and run. This is the output:
[output_eos4vb_cli.csv](https://github.com/ersilia-os/eos4avb/files/10687226/output_eos4vb_cli.csv)

**Comment by Femme-js** [comment]
Hi @GemmaTuron!

The model was fetched successfully on CLI and colab both.

[eos4avb.log](https://github.com/ersilia-os/eos4avb/files/10689679/eos4avb.log)

https://colab.research.google.com/drive/1RP5WQ6dQ97c9ef7wmqZiLb32IlpqHWiw#scrollTo=CHFQjKJ2cuMD
